import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, win32 } from "node:path";
import { writePrivateFileAtomic } from "./safe-local-file.js";

export const WINDOWS_TASK_NAME = "whoburnedmore-sync";

const psQuote = (value: string): string => `'${value.replaceAll("'", "''")}'`;
const encodePowerShell = (script: string): string => Buffer.from(script, "utf16le").toString("base64");

export interface WindowsSyncOptions {
  nodePath: string;
  npmCliPath: string;
  configDir: string;
  commandArgs: string[];
  envPairs: Array<[string, string]>;
  intervalMinutes: number;
  systemRoot: string;
}

export function windowsLauncherPath(opts: WindowsSyncOptions): string {
  return join(opts.configDir, "sync-launcher.js");
}

export function windowsHostPath(opts: WindowsSyncOptions): string {
  return win32.join(opts.systemRoot, "System32", "wscript.exe");
}

/** Locate npm's JS entry point: .cmd files cannot be spawned as executables. */
export function resolveWindowsNpmCli(opts: {
  nodePath?: string;
  env?: NodeJS.ProcessEnv;
  exists?: (path: string) => boolean;
} = {}): string {
  const nodePath = opts.nodePath ?? process.execPath;
  const env = opts.env ?? process.env;
  const exists = opts.exists ?? existsSync;
  const candidates = [
    // Prefer the npm belonging to the captured node runtime over an npx cache.
    win32.join(win32.dirname(nodePath), "node_modules", "npm", "bin", "npm-cli.js"),
    env.npm_execpath,
    env.APPDATA && win32.join(env.APPDATA, "npm", "node_modules", "npm", "bin", "npm-cli.js"),
  ];
  for (const candidate of candidates) {
    if (candidate && win32.isAbsolute(candidate) &&
        win32.basename(candidate).toLowerCase() === "npm-cli.js" && exists(candidate)) return candidate;
  }
  throw new Error("could not locate npm-cli.js for background sync; repair your Node/npm installation and run `whoburnedmore install-sync` again");
}

/**
 * wscript is a GUI-subsystem host: it never allocates a visible console. Its
 * synchronous hidden Run keeps Task Scheduler tracking the actual exit code
 * and prevents overlapping ticks. Hidden=true on a task only hides its listing.
 * Encoded PowerShell transports paths/env without cmd.exe expansion or quoting.
 */
export function buildWindowsLauncher(opts: WindowsSyncOptions): string {
  const log = join(opts.configDir, "sync.log");
  const script = [
    "$ErrorActionPreference = 'Stop'",
    // Node emits UTF-8; Windows PowerShell 5.1 otherwise decodes native output
    // using the console's legacy code page before writing our UTF-8 log.
    `$log = ${psQuote(log)}`,
    "try {",
    "  [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding -ArgumentList $false",
    `  Set-Location -LiteralPath ${psQuote(opts.configDir)}`,
    "  if ((Test-Path -LiteralPath $log) -and (Get-Item -LiteralPath $log).Length -gt 262144) {",
    "    Move-Item -LiteralPath $log -Destination ($log + '.1') -Force",
    "  }",
    ...opts.envPairs.map(([key, value]) => `  $env:${key} = ${psQuote(value)}`),
    // Use Windows' inherited PATH, not the colon-separated Unix sync PATH.
    `  $env:Path = ${psQuote(win32.dirname(opts.nodePath) + ";")} + $env:Path`,
    "  ('[' + [DateTime]::UtcNow.ToString('o') + '] sync started') | Out-File -LiteralPath $log -Append -Encoding utf8",
    // PS 5.1 turns native stderr into error records. Continue preserves npm's
    // true exit code even when a successful run emits warnings on stderr.
    "  $ErrorActionPreference = 'Continue'",
    "  $LASTEXITCODE = 1",
    `  & ${[opts.nodePath, opts.npmCliPath, ...opts.commandArgs].map(psQuote).join(" ")} 2>&1 | Out-File -LiteralPath $log -Append -Encoding utf8`,
    "  $code = $LASTEXITCODE",
    "  ('[' + [DateTime]::UtcNow.ToString('o') + '] sync exited ' + $code) | Out-File -LiteralPath $log -Append -Encoding utf8",
    "  exit $code",
    "} catch {",
    "  $_ | Out-File -LiteralPath $log -Append -Encoding utf8",
    "  exit 1",
    "}",
  ].join("\r\n");
  // Only this trusted system path reaches WshShell.Run's %VAR% expansion;
  // every user-controlled value is inside the encoded payload.
  const command = `"${win32.join(opts.systemRoot, "System32", "WindowsPowerShell", "v1.0", "powershell.exe")}" -NoLogo -NoProfile -NonInteractive -EncodedCommand ${encodePowerShell(script)}`;
  return `// Generated by whoburnedmore; run through wscript, not node.\r\nvar shell = new ActiveXObject("WScript.Shell");\r\nWScript.Quit(shell.Run(${JSON.stringify(command)}, 0, true));\r\n`;
}

function xmlEscape(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&apos;");
}

export function windowsTaskArguments(opts: WindowsSyncOptions): string {
  return `//B //Nologo //E:JScript "${windowsLauncherPath(opts)}"`;
}

export function buildWindowsTaskXml(opts: WindowsSyncOptions, start = new Date()): string {
  return `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <Triggers><TimeTrigger>
    <Repetition><Interval>PT${opts.intervalMinutes}M</Interval><StopAtDurationEnd>false</StopAtDurationEnd></Repetition>
    <StartBoundary>${start.toISOString()}</StartBoundary><Enabled>true</Enabled>
  </TimeTrigger></Triggers>
  <Principals><Principal id="Author"><LogonType>InteractiveToken</LogonType><RunLevel>LeastPrivilege</RunLevel></Principal></Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries><StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <StartWhenAvailable>true</StartWhenAvailable><Enabled>true</Enabled>
    <ExecutionTimeLimit>PT14M</ExecutionTimeLimit>
  </Settings>
  <Actions Context="Author"><Exec>
    <Command>${xmlEscape(windowsHostPath(opts))}</Command>
    <Arguments>${xmlEscape(windowsTaskArguments(opts))}</Arguments>
    <WorkingDirectory>${xmlEscape(opts.configDir)}</WorkingDirectory>
  </Exec></Actions>
</Task>
`;
}

/** Read scheduler XML, not localized schtasks table output. */
export function readWindowsTask(): string | null {
  const res = spawnSync("schtasks.exe", ["/Query", "/TN", WINDOWS_TASK_NAME, "/XML"], {
    windowsHide: true, timeout: 15_000,
  });
  if (res.error) throw new Error(`could not inspect scheduled task: ${res.error.message}`);
  if (res.status !== 0) {
    // Do not silently replace a task when the scheduler itself is inaccessible.
    const probe = spawnSync("schtasks.exe", ["/Query"], {
      encoding: "utf8", windowsHide: true, timeout: 15_000,
    });
    if (probe.status !== 0) throw new Error(`could not inspect scheduled tasks: ${probe.stderr || probe.error?.message || "scheduler unavailable"}`);
    return null;
  }
  return decodeTaskXml(res.stdout);
}

/** schtasks can emit UTF-16 when its XML output is redirected to a pipe. */
export function decodeTaskXml(output: Buffer | string): string {
  if (typeof output === "string") return output.replace(/^\uFEFF/, "");
  const utf16 = (output[0] === 0xff && output[1] === 0xfe) || output[1] === 0;
  return output.toString(utf16 ? "utf16le" : "utf8").replace(/^\uFEFF/, "");
}

function xmlValues(xml: string, tag: string): string[] {
  return [...xml.matchAll(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)</${tag}>`, "g"))]
    .map((match) => match[1].trim().replaceAll("&lt;", "<").replaceAll("&gt;", ">")
      .replaceAll("&quot;", '"').replaceAll("&apos;", "'").replaceAll("&amp;", "&"));
}

export function windowsTaskEnabled(xml: string): boolean {
  const settings = xmlValues(xml, "Settings")[0] ?? "";
  return xmlValues(settings, "Enabled")[0] !== "false";
}

/** Compare semantic fields: scheduler adds defaults, IDs and registration dates. */
export function windowsTaskDrift(
  installed: string | null,
  launcher: string | null,
  opts: WindowsSyncOptions,
): "absent" | "drift" | "ok" {
  if (installed === null) return "absent";
  // Respect an explicit Disable-ScheduledTask; foreground sync must not undo it.
  if (!windowsTaskEnabled(installed)) return "ok";
  if (launcher !== buildWindowsLauncher(opts)) return "drift";
  const expected = buildWindowsTaskXml(opts);
  for (const tag of ["Command", "Arguments", "WorkingDirectory", "Interval", "StopAtDurationEnd",
    "LogonType", "RunLevel", "MultipleInstancesPolicy", "DisallowStartIfOnBatteries",
    "StopIfGoingOnBatteries", "StartWhenAvailable", "ExecutionTimeLimit", "Enabled"]) {
    if (JSON.stringify(xmlValues(installed, tag)) !== JSON.stringify(xmlValues(expected, tag))) return "drift";
  }
  const triggers = xmlValues(installed, "Triggers")[0] ?? "";
  const repetition = xmlValues(triggers, "Repetition")[0] ?? "";
  // Scheduler also adds IdleSettings/Duration by default. Only a repetition
  // duration expires our timer; treating idle duration as drift reinstalls on
  // every successful sync, immediately scheduling yet another run.
  if (xmlValues(triggers, "EndBoundary").length || xmlValues(repetition, "Duration").length ||
      xmlValues(triggers, "TimeTrigger").length !== 1 || xmlValues(triggers, "StartBoundary").length !== 1) return "drift";
  return "ok";
}

export function readWindowsLauncher(opts: WindowsSyncOptions): string | null {
  try { return readFileSync(windowsLauncherPath(opts), "utf8"); } catch { return null; }
}

export function installWindowsSync(opts: WindowsSyncOptions): void {
  if (!existsSync(windowsHostPath(opts))) throw new Error("Windows Script Host is required for windowless background sync");
  const launcher = windowsLauncherPath(opts);
  const previous = readWindowsLauncher(opts);
  const temp = mkdtempSync(join(tmpdir(), "whoburnedmore-task-"));
  try {
    if (!writePrivateFileAtomic(launcher, buildWindowsLauncher(opts), 1024 * 1024)) {
      throw new Error("could not write the Windows background-sync launcher");
    }
    const xmlPath = join(temp, "task.xml");
    // Match the declared XML encoding, including a BOM, for schtasks import.
    writeFileSync(xmlPath, "\uFEFF" + buildWindowsTaskXml(opts), "utf16le");
    const res = spawnSync("schtasks.exe", ["/Create", "/F", "/TN", WINDOWS_TASK_NAME, "/XML", xmlPath], {
      encoding: "utf8", windowsHide: true, timeout: 30_000,
    });
    if (res.status !== 0) throw new Error(`could not create scheduled task: ${res.stderr?.trim() || res.error?.message || res.stdout?.trim() || "unknown scheduler error"}`);
  } catch (error) {
    if (previous === null) rmSync(launcher, { force: true });
    else writePrivateFileAtomic(launcher, previous, 1024 * 1024);
    throw error;
  } finally {
    rmSync(temp, { recursive: true, force: true });
  }
}

export function uninstallWindowsSync(configDir: string): void {
  if (readWindowsTask() !== null) {
    const res = spawnSync("schtasks.exe", ["/Delete", "/F", "/TN", WINDOWS_TASK_NAME], {
      encoding: "utf8", windowsHide: true, timeout: 15_000,
    });
    if (res.status !== 0) throw new Error(`could not remove scheduled task: ${res.stderr || res.error?.message || "unknown scheduler error"}`);
  }
  rmSync(join(configDir, "sync-launcher.js"), { force: true });
}
